version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: es01
    env_file: elastic_variables.env
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02,es03
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: es02
    env_file: elastic_variables.env
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es03
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: es03
    env_file: elastic_variables.env
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic

  # elasticsearch web-ui
  dejavu:
    image: appbaseio/dejavu:3.2.3
    container_name: dejavu
    ports:
     - '1358:1358'
    links:
      - es01
      - es02
      - es03

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge